INSERT INTO productos (PRODUCT_NAME, PRICE, CREATE_AT) VALUES('Samsung LG', 800, NOW());
INSERT INTO productos (PRODUCT_NAME, PRICE, CREATE_AT) VALUES('Motorola Moto G8', 700, NOW());
INSERT INTO productos (PRODUCT_NAME, PRICE, CREATE_AT) VALUES('Oppo X2 Lite', 1000, NOW());
INSERT INTO productos (PRODUCT_NAME, PRICE, CREATE_AT) VALUES('iPhone 8', 1000, NOW());
INSERT INTO productos (PRODUCT_NAME, PRICE, CREATE_AT) VALUES('HTC One', 500, NOW());
INSERT INTO productos (PRODUCT_NAME, PRICE, CREATE_AT) VALUES('ZTE', 600, NOW());
INSERT INTO productos (PRODUCT_NAME, PRICE, CREATE_AT) VALUES('Xiaomi', 100, NOW());
INSERT INTO productos (PRODUCT_NAME, PRICE, CREATE_AT) VALUES('Sony Ericsson', 200, NOW());
INSERT INTO productos (PRODUCT_NAME, PRICE, CREATE_AT) VALUES('Nokia', 300, NOW());